Repository dfdfg42/nyum-tolic, pull requests merged in 2024-04, with the labels that each got.

#17 [FIX] 불필요한 mail관련 환경변수 삭제
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/resources/application.properties
Labels: bug

#18 [FEAT] 별명 변경기능 추가
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/java/com/nyumtolic/nyumtolic/security/controller/UserApiController.java
  src/main/java/com/nyumtolic/nyumtolic/security/dto/UserUpdateForm.java
  src/main/java/com/nyumtolic/nyumtolic/security/oauth/PrincipalDetails.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserService.java
  src/main/resources/static/js/jquery-3.7.1.min.js
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/login_form.html
Labels: enhancement

#21 [FIX] 음식점 별점 정렬 fix
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/java/com/nyumtolic/nyumtolic/repository/RestaurantRepository.java
Labels: bug, enhancement

#22 [FIX} 별점 정렬 오류 fix
  src/main/java/com/nyumtolic/nyumtolic/repository/RestaurantRepository.java
  src/main/java/com/nyumtolic/nyumtolic/service/RestaurantService.java
Labels: bug

#23 [FIX] detail container 일관성 패치
  src/main/resources/templates/restaurant/detail.html
Labels: bug

#24 [Design] list.html 모바일 웹 버전 추가
  src/main/resources/templates/restaurant/list.html
Labels: enhancement

#25 [FIX] navbar 정상화 + 가시성 개선
  src/main/resources/templates/fragments/navbar.html
Labels: bug
