Repository dfdfg42/nyum-tolic, pull requests merged in 2024-05, with the labels that each got.

#26 [Design] recommendation.html 모바일 웹 버전 추가
  src/main/resources/templates/restaurant/recommendation.html
Labels: enhancement

#27 [Design] detail.html 모바일 웹 버전 추가
  src/main/resources/templates/restaurant/detail.html
Labels: enhancement

#28 [Fix] list.html 모바일 버전에서 카테고리 선택시 다중으로 나오던 버그 수정
  src/main/resources/templates/restaurant/list.html
Labels: bug

#30 list.html 모바일 버전에서 카테고리 선택시 다중으로 나오던 버그 수정
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/restaurant/list.html
Labels: bug

#31 [FIX] safari 스크롤 바운싱 문제 & 카드 겹침 현상 제거
  src/main/resources/templates/restaurant/list.html
Labels: bug

#32 [FIX] 카테고리 간략화 모바일 오류
  src/main/resources/templates/restaurant/list.html
Labels: bug

#33 detail.html, recommendation.html 모바일에서 카드 레이아웃 수정 및 카드 부드럽게 나오게 변경
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/restaurant/recommendation.html
Labels: enhancement

#34 [Feat] [Fix] 리뷰 수정시 기존 별점 및 리뷰 확인 가능, PC 웹 송출 겹침 버그 수정
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewController.java
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewService.java
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/restaurant/recommendation.html
  src/main/resources/templates/review_form.html
Labels: bug, enhancement

#35 [FIX] list페이지 반응형 개선
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/resources/application.properties
  src/main/resources/templates/restaurant/list.html
Labels: bug

#37 [FIX] 학식 페이지 일관성 유지
  .gitignore
  Buon Pranzo.pdf
  Buon Pranzo_page_0.jpg
  Cafe Bona.pdf
  Cafe Bona_page_0.jpg
  Cafe Mensa.pdf
  Cafe Mensa_page_0.jpg
  src/main/resources/templates/catholic/menu.html
Labels: bug

#38 [FIX] 벤버튼 복구
  Buon Pranzo_page_0.jpg
  Cafe Bona_page_0.jpg
  Cafe Mensa_page_0.jpg
  src/main/resources/templates/restaurant/detail.html
Labels: bug

#39 [FIX] 랜덤추천 페이지 사파리 반응형 개선
  src/main/resources/templates/restaurant/recommendation.html
Labels: bug

#40 [DOCU] add README
  README.md
Labels: documentation
