Repository dfdfg42/nyum-tolic, pull requests merged in 2024-03, with the labels that each got.

#1 [FIX] 로그아웃 시 2개이상 댓글이 있는 페이지 랜더링 오류
  src/main/resources/application.properties
Labels: bug

#3 test2
  src/main/resources/templates/restaurant/detail.html
Labels: documentation

#4 list.html 수정
  src/main/java/com/nyumtolic/nyumtolic/config/ExcelDataLoader.java
  src/main/resources/Data/nyumData.xlsx
  src/main/resources/static/css/my-fonts.css
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/restaurant/list.html
Labels: documentation

#6 [FEAT] 카카오 소셜 로그인
  .gitignore
  build.gradle
  src/main/java/com/nyumtolic/nyumtolic/controller/RestaurantController.java
  src/main/java/com/nyumtolic/nyumtolic/review/Review.java
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewController.java
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewRepository.java
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewService.java
  src/main/java/com/nyumtolic/nyumtolic/security/config/BCryptConfig.java
  src/main/java/com/nyumtolic/nyumtolic/security/config/SecurityConfig.java
  src/main/java/com/nyumtolic/nyumtolic/security/controller/UserController.java
  src/main/java/com/nyumtolic/nyumtolic/security/domain/SiteUser.java
  src/main/java/com/nyumtolic/nyumtolic/security/domain/UserRole.java
  src/main/java/com/nyumtolic/nyumtolic/security/dto/UserCreateForm.java
  src/main/java/com/nyumtolic/nyumtolic/security/oauth/KakaoUserInfo.java
  src/main/java/com/nyumtolic/nyumtolic/security/oauth/OAuth2UserInfo.java
  src/main/java/com/nyumtolic/nyumtolic/security/oauth/PrincipalDetails.java
  src/main/java/com/nyumtolic/nyumtolic/security/repository/UserRepository.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/PrincipalOauth2UserService.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserSecurityService.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserService.java
  src/main/java/com/nyumtolic/nyumtolic/user/SiteUser.java
  src/main/java/com/nyumtolic/nyumtolic/user/UserRepository.java
  src/main/java/com/nyumtolic/nyumtolic/user/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/login_form.html
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/signup_form.html
Labels: enhancement

#8 [FEAT] 계정 차단 및 IP 차단 기능
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewController.java
  src/main/java/com/nyumtolic/nyumtolic/security/config/SecurityConfig.java
  src/main/java/com/nyumtolic/nyumtolic/security/domain/IpBlackList.java
  src/main/java/com/nyumtolic/nyumtolic/security/domain/SiteUser.java
  src/main/java/com/nyumtolic/nyumtolic/security/filter/IpBlackListFilter.java
  src/main/java/com/nyumtolic/nyumtolic/security/oauth/PrincipalDetails.java
  src/main/java/com/nyumtolic/nyumtolic/security/repository/IpRepository.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/IpService.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/PrincipalOauth2UserService.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserSecurityService.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserService.java
  src/main/java/com/nyumtolic/nyumtolic/security/util/IpUtil.java
Labels: enhancement

#9 [FIX] fix review error
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewController.java
Labels: bug

#10 건의사항, 마이페이지, 리뷰 별점,사진첨부 html 임시 제작(백엔드 구현해야 댐)
  src/main/java/com/nyumtolic/nyumtolic/security/controller/UserController.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/restaurant/detail.html
  src/main/resources/templates/suggestions.html
Labels: documentation

#11 [FEAT] 유저 벤 기능 & 댓글 삭제 기능 추가
  src/main/java/com/nyumtolic/nyumtolic/review/ReviewAdminController.java
  src/main/java/com/nyumtolic/nyumtolic/security/config/CustomSessionInformationExpiredStrategy.java
  src/main/java/com/nyumtolic/nyumtolic/security/config/SecurityConfig.java
  src/main/java/com/nyumtolic/nyumtolic/security/controller/AdminUserController.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserService.java
  src/main/resources/templates/restaurant/detail.html
Labels: enhancement

#12 [FIX] 로그인 후에도 회원가입이 존재하는 버그, 회원관리 페이지 CSS 일관성 패치
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/signup_form.html
  src/main/resources/templates/suggestions.html
Labels: bug

#13 [FIX] 삭제되지 않은 todo 삭제
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCafeTable.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCafeTableRepository.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCrawlerService.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCrawlerUtil.java
  src/main/java/com/nyumtolic/nyumtolic/security/service/UserService.java
  src/test/java/CrawlerTest.java
Labels: bug

#14 [FEAT] 학식 정보 크롤링 및 DB 저장 기능
  build.gradle
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCafeTable.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCafeTableRepository.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCrawlerService.java
  src/main/java/com/nyumtolic/nyumtolic/crawler/CatholicCrawlerUtil.java
  src/test/java/CrawlerTest.java
Labels: enhancement

#15 [FEAT] 학식정보제공 UI/UX
  src/main/java/com/nyumtolic/nyumtolic/catholic/CatholicCafeController.java
  src/main/java/com/nyumtolic/nyumtolic/catholic/CatholicCafeTable.java
  src/main/java/com/nyumtolic/nyumtolic/catholic/CatholicCafeTableRepository.java
  src/main/java/com/nyumtolic/nyumtolic/catholic/CatholicCrawlerService.java
  src/main/java/com/nyumtolic/nyumtolic/catholic/CatholicCrawlerUtil.java
  src/main/resources/templates/catholic/menu.html
  src/main/resources/templates/fragments/navbar.html
  src/test/java/CrawlerTest.java
Labels: enhancement

#16 [FIX] 설장파일 변경
  .gitignore
  src/main/resources/application.properties
Labels: enhancement
